# Generated by Django 2.0.6 on 2018-07-04 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendanceStatus', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=250)),
                ('datetime', models.DateTimeField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audience', models.ManyToManyField(related_name='group_events', to='auth.Group')),
                ('createdBy', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='owned_events', to=settings.AUTH_USER_MODEL)),
                ('helpers', models.ManyToManyField(related_name='manytomanyevents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('rollno', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='eventName', to='api.event'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
