# Generated by Django 2.0.6 on 2018-07-05 13:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='complaintEvent', to='api.event')),
            ],
        ),
    ]
