# Generated by Django 2.0.6 on 2018-07-05 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_complaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='description',
            new_name='message',
        ),
        migrations.AddField(
            model_name='complaint',
            name='user',
            field=models.ManyToManyField(related_name='complaint', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='event',
        ),
        migrations.AddField(
            model_name='complaint',
            name='event',
            field=models.ManyToManyField(related_name='complaintEvent', to='api.event'),
        ),
    ]
