# Generated by Django 2.0.6 on 2018-06-25 10:49

from django.db import migrations, models
from datetime import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180617_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(default=datetime.now()),
            preserve_default=False,
        ),
    ]
