# Generated by Django 2.0.6 on 2018-06-25 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_event_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='createdBy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
