# Generated by Django 2.0.6 on 2018-07-05 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20180705_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='event',
        ),
        migrations.AddField(
            model_name='complaint',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='complaintEvent', to='api.event'),
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='user',
        ),
        migrations.AddField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='complaintUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
