# Generated by Django 2.0.6 on 2018-06-26 12:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180626_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='helpers',
            field=models.ManyToManyField(related_name='manytomanyevents', to=settings.AUTH_USER_MODEL),
        ),
    ]
