# Generated by Django 2.0.6 on 2018-06-26 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180626_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='createdBy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='owned_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
