# Generated by Django 2.0.6 on 2018-07-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180705_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='resolutionStatus',
            field=models.BooleanField(default=False),
        ),
    ]
