# Generated by Django 2.0.6 on 2018-06-27 09:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_auto_20180626_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='audience',
        ),
        migrations.AddField(
            model_name='event',
            name='audience',
            field=models.ManyToManyField(related_name='group_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
