# Generated by Django 2.0.6 on 2018-07-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_complaint_resolutionstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolutionStatus',
            field=models.BooleanField(default=False),
        ),
    ]
