# Generated by Django 2.0.6 on 2018-06-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180627_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='audience',
            field=models.ManyToManyField(related_name='group_events', to='auth.Group'),
        ),
    ]
