# Generated by Django 2.0.6 on 2018-07-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_complaint_resolutionstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='createdDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
