# Generated by Django 2.0.6 on 2018-07-09 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_complaint_createddatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='eventName', to='api.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='helpers',
            field=models.ManyToManyField(blank=True, related_name='manytomanyevents', to=settings.AUTH_USER_MODEL),
        ),
    ]
