# Generated by Django 2.0.6 on 2018-07-09 15:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180709_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdeviceidandauthtoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
